/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./client/index.html",
    "./client/src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#f0bd8b",
        "on-tertiary-container": "#ea7253",
        "outline-variant": "#d3c3bd",
        "on-primary-fixed": "#281810",
        "secondary-fixed": "#ffdcbd",
        "on-tertiary-fixed": "#3c0700",
        "surface-dim": "#dbdbcf",
        "on-secondary-fixed": "#2c1600",
        "background": "#fbfaee",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-variant": "#e4e3d7",
        "tertiary-fixed-dim": "#ffb4a2",
        "surface-container-low": "#f5f4e8",
        "error": "#ba1a1a",
        "outline": "#81756f",
        "tertiary-fixed": "#ffdad2",
        "on-surface": "#1b1c15",
        "on-secondary-fixed-variant": "#623f18",
        "on-secondary": "#ffffff",
        "surface": "#fbfaee",
        "on-primary-fixed-variant": "#574238",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e4e3d7",
        "on-error-container": "#93000a",
        "on-secondary-container": "#7a532a",
        "primary": "#25160e",
        "primary-fixed": "#fbdcce",
        "surface-container": "#efeee3",
        "primary-fixed-dim": "#dec1b3",
        "primary-container": "#3c2a21",
        "on-tertiary-fixed-variant": "#83260e",
        "tertiary-container": "#5d1000",
        "secondary": "#7d562d",
        "inverse-surface": "#303129",
        "on-background": "#1b1c15",
        "surface-bright": "#fbfaee",
        "tertiary": "#380600",
        "on-surface-variant": "#4f4540",
        "secondary-container": "#ffca98",
        "on-primary-container": "#aa9084",
        "surface-container-high": "#e9e9dd",
        "surface-tint": "#705a4f",
        "inverse-primary": "#dec1b3",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f2f1e5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "stack-md": "16px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "stack-lg": "32px",
        "unit": "8px",
        "stack-sm": "8px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
